Basic setup and Index routes
thapar-vansh/Intern-Assignment-2 pull request #1
Opened 2022-03-21 06:18 UTC by thapar-vansh

2022-04-05 13:10 UTC, jagdishcm-sixer requested changes

2022-04-05 13:10 UTC, jagdishcm-sixer commented on routes/indexRoutes.ts
> +export const router = express.Router()
Type ??

2022-04-05 13:10 UTC, jagdishcm-sixer commented on controllers/adminController.ts
> +  if (!name || !country) {
should be && instead of ||

2022-04-05 13:10 UTC, jagdishcm-sixer commented on controllers/adminController.ts
> +  if (!id || !name || !country) {
id should be mandatory. name and country can be optional

2022-04-05 13:10 UTC, jagdishcm-sixer commented on controllers/indexController.ts
> +  if (!username || !password) {
should be && instead of ||

2022-04-05 13:10 UTC, jagdishcm-sixer commented on controllers/indexController.ts
> +  if (!username || !password) {
should be && instead of ||

2022-04-05 13:10 UTC, jagdishcm-sixer commented on database/players.db.ts
> +// const players: string[] = []
remove all the unneeded commented code before creating a PR

2022-04-05 13:10 UTC, jagdishcm-sixer commented on middleware/auth.ts
> +    const decoded = jwt.verify(token, config.JWT_PRIVATEKEY)
Type ?

2022-04-05 13:10 UTC, jagdishcm-sixer commented on middleware/auth.ts
> +    const user = await getUserByUserId(req.userToken['userId'])
Type ?

2022-04-05 13:10 UTC, jagdishcm-sixer commented on routes/adminRoutes.ts
> +export const router = express.Router()
Type ?

2022-04-18 13:31 UTC, Sachin-R-Yawalkar requested changes

2022-04-18 13:31 UTC, Sachin-R-Yawalkar commented on services/loginService.ts
> +export function generateToken(userId: number): string {
Change this to es6 function

2022-04-18 13:32 UTC, jagdishcm-sixer requested changes

2022-04-18 13:32 UTC, jagdishcm-sixer commented on tests/services/adminService.test.ts
> +      })
while committing code, check if code has been formatted correctly
PS : checkout prettier code formatter

2022-04-18 13:32 UTC, jagdishcm-sixer commented on tests/services/adminService.test.ts
> +      })
add negative tests as well 
e.g. when user tries to fetch player with invalid name

2022-04-18 13:32 UTC, jagdishcm-sixer commented on tests/services/loginService.test.ts
> +    const expectedUsers = [
put these expected values in a different file to keep the code clean

2022-04-18 13:32 UTC, jagdishcm-sixer commented on tests/services/loginService.test.ts
> +      .mockImplementation(() => Promise.resolve(registerUser('vansh','India@07')))
it's not the correct way of mocking a function for unit test

2022-04-18 13:32 UTC, jagdishcm-sixer commented on tests/services/userService.test.ts
> +      //console.log(await checkDuplicateFav(1,20),await checkDuplicateFav(1,2))
remove the comments and logs too

2022-04-18 13:32 UTC, jagdishcm-sixer commented on tests/services/userService.test.ts
> +    console.log(result1)
remove logs

2022-04-18 13:32 UTC, jagdishcm-sixer commented on tests/services/userService.test.ts
> +    console.log(result1,result2)
remove logs

2022-04-27 12:58 UTC, jagdishcm-sixer requested changes

2022-04-27 12:58 UTC, jagdishcm-sixer commented on tests/services/loginService.test.ts
> +  it('register user', async () => {
also specify if test is getting successful or failed

2022-04-27 12:58 UTC, jagdishcm-sixer commented on tests/services/loginService.test.ts
> +    const mockGenerateToken = jest
you need to mock getUserbyUsername function as well

2022-04-27 13:02 UTC, Sachin-R-Yawalkar requested changes

2022-04-27 13:02 UTC, Sachin-R-Yawalkar commented on tests/services/loginService.test.ts
> +    expect(result).toBe(undefined)
action: need to mock this function as well `await addUserToDb(username, hashedPassword)`

2022-04-27 13:02 UTC, Sachin-R-Yawalkar commented on tests/services/userService.test.ts
> +    const mockCheckDuplicateFav = jest
action: need to mock `await getPlayerById(id)` before

2022-04-27 13:02 UTC, Sachin-R-Yawalkar commented on tests/services/userService.test.ts
> +    const mockCheckDuplicateFav = jest
same as above

2022-05-11 13:17 UTC, jagdishcm-sixer approved these changes

2022-05-11 13:17 UTC, Sachin-R-Yawalkar approved these changes
Good Work! Approved

2022-05-11 13:17 UTC, merged