axios
thapar-vansh/Intern-Assignment-2 pull request #4
Opened 2022-05-19 13:29 UTC by thapar-vansh

2022-05-20 12:30 UTC, Sachin-R-Yawalkar requested changes

2022-05-20 12:30 UTC, Sachin-R-Yawalkar commented on controllers/axiosController.ts
> +  const response = await axios.get('https://jsonplaceholder.typicode.com/posts')
Action: add axios request in try catch block

2022-05-20 12:30 UTC, Sachin-R-Yawalkar commented on controllers/axiosController.ts
> +    await axios.post('https://jsonplaceholder.typicode.com/posts', data)
What will happen if this fails?

2022-05-20 12:30 UTC, Sachin-R-Yawalkar commented on controllers/axiosController.ts
> +    await axios.post('https://jsonplaceholder.typicode.com/posts', data)
What will happen if this fails?

2022-05-20 12:30 UTC, Sachin-R-Yawalkar commented on controllers/axiosController.ts
> +    await axios.delete('https://jsonplaceholder.typicode.com/posts/1')
What will happen if this fails?

2022-05-24 12:39 UTC, jagdishcm-sixer requested changes

2022-05-24 12:39 UTC, jagdishcm-sixer commented on controllers/axiosController.ts
> +    await axios.post('https://jsonplaceholder.typicode.com/posts', data)
You can put the url in some common file like constants or env file.

2022-05-24 12:39 UTC, jagdishcm-sixer commented on controllers/axiosController.ts
> +    await axios.post('https://jsonplaceholder.typicode.com/posts', data)
You can add one more check for response code if it's 200 or not.

2022-06-27 13:13 UTC, jagdishcm-sixer approved these changes

2022-07-05 13:38 UTC, Sachin-R-Yawalkar approved these changes

2022-07-05 13:38 UTC, merged